version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt protocol
    environment:
      # Authentication (username/password)
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      # Memory allocation
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_dbms_usage__report_enabled=false
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/plugins:/plugins
    user: 501:20
